stages:
  prepare_data:
    cmd: python scripts/prepare_data.py
    deps:
      - data/raw_data.csv
    outs:
      - data/processed_data.csv

  train:
    cmd: python scripts/train.py
    deps:
      - data/processed_data.csv
      - scripts/train.py
    outs:
      - models/model.pkl
      - metrics/train_metrics.json

  evaluate:
    cmd: python scripts/evaluate.py
    deps:
      - models/model.pkl
      - data/test_data.csv
    outs:
      - metrics/eval_metrics.json
